name: Deploy to GCP

on:
  push:
    branches:
      - dev
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      TF_VAR_PROJECT_ID: ${{ secrets.PROJECT_ID }}
      TF_VAR_REGION: ${{ vars.REGION }}
      BUCKET_MAIN: ${{ vars.BUCKET_MAIN }}
      BUCKET_DEV: ${{ vars.BUCKET_DEV }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Select workspace
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            terraform workspace select prod || terraform workspace new prod
            echo "TF_VAR_BUCKET_NAME=${{ vars.BUCKET_MAIN }}" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            terraform workspace select dev || terraform workspace new dev
            echo "TF_VAR_BUCKET_NAME=${{ vars.BUCKET_DEV }}" >> $GITHUB_ENV
          fi

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false

  lint:
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm install

      - name: Run Lint
        run: |
          npm run lint

  build:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build Vite project
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: vite-build
          path: ./dist

  upload_to_gcs:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: vite-build

      - name: Install Google Cloud SDK
        run: |
          echo "Installing Google Cloud SDK..."
          curl -sSL https://sdk.cloud.google.com | bash
          source $HOME/google-cloud-sdk/path.bash.inc
          gcloud --version

      - name: Authenticate with GCP
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "${GOOGLE_CREDENTIALS}" > ${HOME}/gcloud-key.json
          gcloud auth activate-service-account --key-file=${HOME}/gcloud-key.json

      - name: Select bucket
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "BUCKET_NAME=${{ vars.BUCKET_MAIN }}" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            echo "BUCKET_NAME=${{ vars.BUCKET_DEV }}" >> $GITHUB_ENV
          fi

      - name: Upload artifact to GCS
        run: |
          gsutil cp -r ./dist/* gs://${BUCKET_NAME}/
